version: '3.5'
services:
  dynamic-dns:
    container_name: dynamic-dns
    image: joweisberg/dynamic-dns:latest
    restart: unless-stopped
    environment:
      - TZ={TIME_ZONE}
      - SERVICE=${SERVICE}
      - USER=${USERNAME}
      - PASSWORD=${PASSWORD}
      - HOSTNAME={DOMAIN}
    healthcheck:
      test: /usr/bin/healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
